### PR TITLE
added functionality to enable or disable the extension

### PR DESCRIPTION
**Pull request by aryangupta701**
Added functionality to enable or disable the extension using options page

### CODE REVIEW

**Comment by thc202** [comment]
The commit still has the typo.

**Comment by psiinon** [comment]
It is now always resetting my ZAP URL to http://localhost:8080/
I run ZAP on a different port, so its no broken for me 😦 
Note that this could have been a previous change...

**Review by psiinon — APPROVED** [review]
I think the problems I had were to do with local Firefox perms. We may well need to document these, but thats unrelated to this PR.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
