### PR TITLE
Remove `package-lock.json`

### PR DESCRIPTION
**Pull request by thc202**
The project is using `yarn` which uses its own lock file.

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by aryangupta701** [comment]
Without a package lock file, a package manager such as Yarn or npm will resolve the the most current version of a package in real-time during the dependencies install of a package, rather than the version that was originally intended for the specific package.

**Comment by aryangupta701** [comment]
Might break the functionality sometimes : https://snyk.io/blog/what-is-package-lock-json/

**Comment by thc202** [comment]
Doesn't `yarn` use its own lock file? i.e. https://github.com/zaproxy/browser-extension/blob/057646134d798672e9a74db680373e1594b1f9c5/yarn.lock

See also: https://github.com/zaproxy/browser-extension/actions/runs/5729172357/job/15525352837#step:4:6

**Comment by aryangupta701** [comment]
ohh got it. Its `yarn.lock` I got confused between the two.

**Review by psiinon — APPROVED** [review]

**Pull request merged**
