### PR TITLE
Init to http://zap/

### PR DESCRIPTION
**Pull request by aryangupta701**

### CODE REVIEW

**Comment by aryangupta701** [comment]
woohoo.. I wonder why they don't pass in my local setup. Is this same with you @psiinon ?

**Review by psiinon — APPROVED** [review]
Nice one!

**Comment by psiinon** [comment]
Will check...

**Comment by psiinon** [comment]
Passes except for the Firefox test for me locally, but that fails without this change so I think its ok..

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you both!

**Pull request merged**
